SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, PRICE*SUMS AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS SUMS FROM FOOD_ORDER WHERE SUBSTRING(PRODUCE_DATE, 1,7)='2022-05' GROUP BY PRODUCT_ID) AS T 
	JOIN FOOD_PRODUCT
	ON(T.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID)
ORDER BY TOTAL_SALES DESC;