SELECT PRICE_DIV*10000, COUNT(T.PRODUCT_ID) AS PRODUCTS
FROM (SELECT PRODUCT_ID, PRICE DIV 10000 AS PRICE_DIV
FROM PRODUCT) AS T JOIN PRODUCT
ON T.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRICE_DIV
ORDER BY PRICE_DIV;