SELECT FIRST_HALF.FLAVOR
FROM (SELECT *
     FROM FIRST_HALF
     WHERE TOTAL_ORDER>3000) AS FIRST_HALF 
     JOIN 
     (SELECT * 
     FROM ICECREAM_INFO 
     WHERE INGREDIENT_TYPE = 'fruit_based') AS ICECREAM_INFO
ON(FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR)
ORDER BY TOTAL_ORDER DESC;