SELECT T.YEAR, T.MONTH, USER_INFO.GENDER, COUNT(DISTINCT(T.USER_ID)) AS USERS
FROM (SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
     FROM ONLINE_SALE 
     ) AS T JOIN (SELECT *
                  FROM USER_INFO
                 WHERE GENDER IS NOT NULL) AS USER_INFO
ON(T.USER_ID = USER_INFO.USER_ID)
GROUP BY T.YEAR, T.MONTH, USER_INFO.GENDER
HAVING USER_INFO.GENDER IS NOT NULL
ORDER BY T.YEAR, T.MONTH, USER_INFO.GENDER;