SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID
WHERE SUBSTR(SEX_UPON_INTAKE,0,INSTR(SEX_UPON_INTAKE,' '))='Intact '
      AND SUBSTR(SEX_UPON_OUTCOME,0,INSTR(SEX_UPON_OUTCOME,' '))!='Intact ';