SELECT T.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM (SELECT * FROM REST_INFO WHERE SUBSTRING(ADDRESS,1,3)='서울시' OR SUBSTRING(ADDRESS,1,5)='서울특별시') AS T JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) AS T2
    ON(T.REST_ID = T2.REST_ID)

ORDER BY SCORE DESC, FAVORITES DESC;