SELECT T.CATEGORY, T.PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT 
GROUP BY CATEGORY) AS T
ON (T.PRICE = FOOD_PRODUCT.PRICE AND T.CATEGORY = FOOD_PRODUCT.CATEGORY)
WHERE T.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY T.PRICE DESC;