SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM(SELECT ONLINE_SALE_ID, PRODUCT_ID, USER_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    WHERE SUBSTRING(SALES_DATE,1,7)='2022-03'
     
    UNION ALL
     
    SELECT OFFLINE_SALE_ID, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE 
    WHERE SUBSTRING(SALES_DATE,1,7)='2022-03') AS T
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;