SELECT T.FOOD_TYPE, REST_ID, REST_NAME, F
FROM REST_INFO JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS F
FROM REST_INFO 
GROUP BY FOOD_TYPE) AS T
ON REST_INFO.FAVORITES = T.F AND REST_INFO.FOOD_TYPE = T.FOOD_TYPE
ORDER BY REST_INFO.FOOD_TYPE DESC;